---
- name: Check OS Version to Target Server
  hosts: all
  remote_user: ec2-user
  gather_facts: yes
  tasks:
    - debug:
        msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
